server:
  port: 3002

spring:
  # 데이터베이스 설정
  datasource:
    driverClassName: '{cipher}ff8ef8169d1c3d5607fd208e5a036e4b0e590ea51f078ef62b678320325af2b7e848b026568c5001833ac3ec2e540554'
    #driverClassName: oracle.jdbc.driver.OracleDriver #암호화할 클래스명
    url: '{cipher}67250ea20eef911c55da72e66058e93b7bc1ba485284c63c0868d382588364aabe5b0f5a9fa14947ac8339e9bbfab238463452a81a06be150f5565c1cf97a2ed'
    #url: jdbc:oracle:thin:@${db.host}:${db.port}:XE #암호화할 포트
    username: ${db.username}
    password: ${db.password}

  # JPA 설정
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddlAuto: create #작업에 따라 적절히 변경

  # 파일 업로드 용량 설정
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 60MB
      fileSizeThreshold: 30MB

  # 정적 자원 설정(CSS, JS, 이미지)
  web:
    resources:
      staticLocations: classpath:/static/
      #staticLocations: file:src/main/resources/static/ #해당 주소로 배포하면 안되기 때문에 변경

  #타임리프 설정
  thymeleaf:
    cache: true
    prefix: classpath:/templates/


# 로거 설정
logging:
  level:
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace

#파일 업로드 경로 설정
file:
  upload:
    path: ${file.path} #환경변수로 환경에 맞게 유연하게 사용
    url: /upload/

# 유레카 설정
#도메인 주소는 찾지 못하기 때문에 IP 주소로 탐색
eureka:
  instance:
    preferIpAddress: true

  #API 서버가 유레카 서버를 찾아야 하기 때문에 true로 설정
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:3101/eureka/ #${eurekaHost}/eureka/

# 액츄에이터 설정
management:
  endpoint:
    health:
      showDetails: always #자세한 정보 보여줌, 일부는 보이지 않게 함
    refresh:
      enabled: true #설정 새로고침, @Value가 붙은 값만..
  endpoints:
    web:
      exposure:
        include: refresh, health #활성화

