server:
  port: 3101 #유레카 서버 포트번호

eureka:
  instance:
    hostname: localhost #${eurekaHost} 환경변수 인식 불가 이슈

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone:
        - http://${eureka.instance.hostname}:${server.port}/eureka/
      #${eureka.instance.hostname} #내부 속성도 접근 가능
    #유레카 서버는 찾지 않아도 되기 때문에 false
    #api나 게이트웨이 등 다른 서버는 찾아야 하기 때문에 true로 설정한다

  #유레카 서버는 클라이언트에게 오는 신호를 받음
  #신호를 못받는 경우 주기적으로 신호 수신 체크함
  server:
    waitTimeInMsWhenSyncEmpty: 30000 # 30초에 한번씩 인스턴스 검색,  1microSec
